# Generated by Django 3.0.5 on 2020-04-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_type', models.CharField(blank=True, choices=[('Copper', 'Медь'), ('Brass', 'Латунь'), ('Steel', 'Сталь'), ('Cast iron', 'Чугун'), ('Stainless Steel', 'Нержавеющая Сталь'), ('Carbon Steel', 'Углеродистая Сталь'), ('Instrumental Steel', 'Инструментальная Сталь'), ('PFE', 'Фторопласт'), ('Nylon', 'Капролон'), ('FR-4', 'Стеклотекстолит'), ('Zedex', 'Zedex'), ('Textolite', 'Текстолит'), ('Aluminium', 'Алюминий')], default='Steel', max_length=20)),
                ('mat_name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('mat_gost', models.CharField(max_length=40)),
                ('density', models.IntegerField()),
            ],
            options={
                'ordering': ['mat_type'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('notice_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('rel', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['rel'],
            },
        ),
        migrations.CreateModel(
            name='TechProp',
            fields=[
                ('draw_num', models.CharField(help_text='Введите номер чертежа', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Номер чертежа')),
                ('name', models.CharField(help_text='Введите название детали', max_length=20, verbose_name='Название детали')),
                ('draw_url', models.URLField(blank=True, verbose_name='Ссылка на чертеж')),
                ('punchable', models.BooleanField(choices=[(True, True), (False, False)], verbose_name='ШТ')),
                ('machinable', models.BooleanField(choices=[(True, True), (False, False)], verbose_name='ИП')),
                ('solder', models.BooleanField(choices=[(True, True), (False, False)], verbose_name='СП')),
                ('assembly', models.BooleanField(choices=[(True, True), (False, False)], verbose_name='СКД')),
                ('galvan', models.BooleanField(choices=[(True, True), (False, False)], verbose_name='ГАЛ')),
                ('subdivision', models.CharField(blank=True, choices=[('MV1', 'ПКГ'), ('MV2', 'ЛКГ'), ('QR1', 'ПКРиФ'), ('QR2', 'ПКЭ'), ('PKO', 'ПКиО')], default=None, max_length=5, verbose_name='Заказчик')),
                ('accept', models.CharField(blank=True, choices=[('VP', 'ВП(5)'), ('OTK', 'ОТК(1)')], default='O-vi', max_length=20)),
                ('coating', models.CharField(blank=True, choices=[('O-vi', 'Олово-висмут'), ('NPb', 'Никель полублестящий'), ('Ag', 'Серебро'), ('None', 'б/п')], default='O-vi', max_length=20, verbose_name='Покрытие')),
                ('draw_mat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technolog.Material', verbose_name='Материал')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technolog.Notice')),
            ],
            options={
                'ordering': ['subdivision', 'name', 'draw_num'],
            },
        ),
    ]
