# Generated by Django 3.0.5 on 2020-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techprop',
            name='name',
            field=models.CharField(help_text='Введите название детали', max_length=15, verbose_name='Название детали'),
        ),
    ]
